const MusicArray = [
  {
    songName: "hopar",
    artistName: "Benyamin",
    src: "alo.mp3",
    id: "1 ",
    genre: "Rap",
  },
  {
    songName: "aper",
    artistName: "Tozduman",
    src: "aloo.mp3",
    id: "2 ",
    genre: "Classic",
  },
  {
    songName: "exo",
    artistName: "Garnik",
    src: "alooo.mp3",
    id: "3 ",
    genre: "Popular",
  },
  {
    songName: "xareb",
    artistName: "Bayxush",
    src: "aloooo.mp3",
    id: "4 ",
    genre: "Hip hop",
  },
  {
    songName: "ara",
    artistName: "Gaspar",
    src: "alooooo.mp3",
    id: "5 ",
    genre: "Metal",
  },
  {
    songName: "hopar",
    artistName: "Benyamin",
    src: "alo.mp3",
    id: "6 ",
    genre: "Popular",
  },
  {
    songName: "aper",
    artistName: "Tozduman",
    src: "aloo.mp3",
    id: "7 ",
    genre: "Funk",
  },
  {
    songName: "exo",
    artistName: "Garnik",
    src: "alooo.mp3",
    id: "8 ",
    genre: "Jazz",
  },
  {
    songName: "xareb",
    artistName: "Bayxush",
    src: "aloooo.mp3",
    id: "9 ",
    genre: "Pop",
  },
  {
    songName: "ara",
    artistName: "Gaspar",
    src: "alooooo.mp3",
    id: "10 ",
    genre: "Pop",
  },
  {
    songName: "hopar",
    artistName: "Benyamin",
    src: "alo.mp3",
    id: "11 ",
    genre: "Funk",
  },
  {
    songName: "aper",
    artistName: "Tozduman",
    src: "aloo.mp3",
    id: "12 ",
    genre: "Rock",
  },
  {
    songName: "exo",
    artistName: "Garnik",
    src: "alooo.mp3",
    id: "13 ",
    genre: "Rip hop",
  },
  {
    songName: "xareb",
    artistName: "Bayxush",
    src: "aloooo.mp3",
    id: "14 ",
    genre: "Rap",
  },
  {
    songName: "ara",
    artistName: "Gaspar",
    src: "alooooo.mp3",
    id: "15 ",
    genre: "Pop",
  },
];
export default MusicArray;
