const MusicArray = [
  {
    songName: "hopar",
    artistName: "Benyamin",
    src: "alo.mp3",
    id: "1 ",
    genre: "rap",
  },
  {
    songName: "aper",
    artistName: "Tozduman",
    src: "aloo.mp3",
    id: "2 ",
    genre: "classic",
  },
  {
    songName: "exo",
    artistName: "Garnik",
    src: "alooo.mp3",
    id: "3 ",
    genre: "popular",
  },
  {
    songName: "xareb",
    artistName: "Bayxush",
    src: "aloooo.mp3",
    id: "4 ",
    genre: "hip hop",
  },
  {
    songName: "ara",
    artistName: "Gaspar",
    src: "alooooo.mp3",
    id: "5 ",
    genre: "metal",
  },
  {
    songName: "hopar",
    artistName: "Benyamin",
    src: "alo.mp3",
    id: "6 ",
    genre: "rock",
  },
  {
    songName: "aper",
    artistName: "Tozduman",
    src: "aloo.mp3",
    id: "7 ",
    genre: "funk",
  },
  {
    songName: "exo",
    artistName: "Garnik",
    src: "alooo.mp3",
    id: "8 ",
    genre: "jazz",
  },
  {
    songName: "xareb",
    artistName: "Bayxush",
    src: "aloooo.mp3",
    id: "9 ",
    genre: "pop",
  },
  {
    songName: "ara",
    artistName: "Gaspar",
    src: "alooooo.mp3",
    id: "10 ",
    genre: "pop",
  },
  {
    songName: "hopar",
    artistName: "Benyamin",
    src: "alo.mp3",
    id: "11 ",
    genre: "funk",
  },
  {
    songName: "aper",
    artistName: "Tozduman",
    src: "aloo.mp3",
    id: "12 ",
    genre: "rock",
  },
  {
    songName: "exo",
    artistName: "Garnik",
    src: "alooo.mp3",
    id: "13 ",
    genre: "hip hop",
  },
  {
    songName: "xareb",
    artistName: "Bayxush",
    src: "aloooo.mp3",
    id: "14 ",
    genre: "rap",
  },
  {
    songName: "ara",
    artistName: "Gaspar",
    src: "alooooo.mp3",
    id: "15 ",
    genre: "pop",
  },
];
export default MusicArray;
