const MusicArray = [
  {
    songName: "Tomorrow",
    artistName: "James Cater",
    src: "James Carter - Tomorrow.mp3",
    id: "1 ",
    genre: "Pop",
  },
  {
    songName: "Lesson Learned",
    artistName: "Matt Hansen",
    src: "Matt Hansen - Lesson Learned.mp3",
    id: "2 ",
    genre: "Pop",
  },
  {
    songName: "Can I Call You Mine",
    artistName: "myle",
    src: "Myle - Can I Call You Mine.mp3",
    id: "3 ",
    genre: "Pop",
  },
  {
    songName: "Ракета",
    artistName: "Alena Sky",
    src: "Alena Sky - Ракета.mp3",
    id: "4 ",
    genre: "Pop",
  },
  {
    songName: "Contento",
    artistName: "Morad",
    src: "Morad - Contento.mp3",
    id: "5 ",
    genre: "Rap",
  },
  {
    songName: "Jacked",
    artistName: "Nippandab",
    src: "Nippandab - Jacked.mp3",
    id: "6 ",
    genre: "Rap",
  },
  {
    songName: "NLE Choppa",
    artistName: "Slut Me Out 2",
    src: "NLE Choppa - Slut Me Out 2.mp3",
    id: "7 ",
    genre: "Rap",
  },
  {
    songName: "TERRY feat Slame ",
    artistName: "No Love",
    src: "TERRY feat Slame - No Love.mp3",
    id: "8 ",
    genre: "Rap",
  },
  {
    songName: "Без Пяти",
    artistName: "Ни О Чем",
    src: "Без Пяти - Ни О Чем.mp3",
    id: "9 ",
    genre: "Rock",
  },
  {
    songName: "Adamant",
    artistName: "Местами",
    src: "Adamant - Местами.mp3",
    id: "10 ",
    genre: "Rock",
  },
  {
    songName: "Blues Pills",
    artistName: "Birthday",
    src: "Blues Pills - Birthday.mp3",
    id: "11 ",
    genre: "Rock",
  },
  {
    songName: "TOBE",
    artistName: "На Луну",
    src: "TOBE - На Луну.mp3",
    id: "12 ",
    genre: "Rock",
  },
  {
    songName: "Of the Earth",
    artistName: "Doug Kaufman",
    src: "Doug Kaufman - Of the Earth.mp3",
    id: "13 ",
    genre: "Classic",
  },
  {
    songName: "Rising",
    artistName: "Laurence Ipsum",
    src: "Laurence Ipsum - Rising.mp3",
    id: "14",
    genre: "Classic",
  },
  {
    songName: "101 Strings",
    artistName: "Goodbye",
    src: "101 Strings - Goodbye.mp3",
    id: "15",
    genre: "Classic",
  },
  {
    songName: "I'm Just A",
    artistName: " Lucas Jayden",
    src: "Lucas Jayden - I'm Just A.mp3",
    id: "16",
    genre: "Classic",
  },
  {
    songName: "Flesh Hunter",
    artistName: "Godless Crusade",
    src: "Godless Crusade - Flesh Hunter.mp3",
    id: "17",
    genre: "Metal",
  },
  {
    songName: "Il Malocchio Si Apre",
    artistName: "Pagan ",
    src: "Pagan - Il Malocchio Si Apre.mp3",
    id: "18",
    genre: "Metal",
  },
  {
    songName: "Pain Relief",
    artistName: "Infected Cells",
    src: "Infected Cells - Pain Relief.mp3",
    id: "19",
    genre: "Metal",
  },
  {
    songName: "Nanook of the North",
    artistName: "Anvil",
    src: "Anvil - Nanook of the North.mp3",
    id: "20",
    genre: "Metal",
  },
  {
    songName: "Catharsis",
    artistName: "Beneath My Shade",
    src: "Beneath My Shade – Catharsis.mp3",
    id: "21",
    genre: "Funk",
  },
  {
    songName: "Follow for Now",
    artistName: "Sway & Tech",
    src: "Sway & Tech - Follow for Now .mp3",
    id: "22",
    genre: "Hip Hop",
  },
  {
    songName: "What I Need",
    artistName: "The Sololution",
    src: "The Sololution - What I Need.mp3",
    id: "23",
    genre: "Hip Hop",
  },
  {
    songName: "WC",
    artistName: "Worldwide Gunnin",
    src: "WC - Worldwide Gunnin.mp3",
    id: "24",
    genre: "Hip Hop",
  },
  {
    songName: "Twinz ",
    artistName: "Round & Round",
    src: "Twinz - Round & Round.mp3",
    id: "25",
    genre: "Hip Hop",
  },
  {
    songName: "Staring At The Wall ",
    artistName: "Norah Jones",
    src: "Norah Jones - Staring At The Wall.mp3",
    id: "26",
    genre: "Jazz",
  },

  {
    songName: "Throughout",
    artistName: "Unscientific Italians ",
    src: "Unscientific Italians - Throughout.mp3",
    id: "27",
    genre: "Jazz",
  },
  {
    songName: "Echo Sax End",
    artistName: "Caleb Arredondo",
    src: "Caleb Arredondo - Echo Sax End.mp3",
    id: "28",
    genre: "Jazz",
  },
];
export default MusicArray;
